# Dockerfile untuk mengkonsumsi image hildakholifahh/my-static-site
FROM hildakholifahh/my-static-site:latest

# Image ini sudah dikonfigurasi dengan baik, hanya menggunakannya langsung
# Jika perlu modifikasi, tambahkan instruksi di sini
